### ISSUE TITLE
Adding/Creating repository fails

### ISSUE THREAD

**Issue by xuv** [pitaj/wengit#3]
Just Trying to add a local repository or create a new one. 
Button `Creating New Repository` never lights up.
![2016-02-16-120109_1920x1080_scrot](https://cloud.githubusercontent.com/assets/192539/13083931/1fbf47b4-d4a5-11e5-837c-1f7f72acb222.png)

Am I doing something wrong? 
Using node v5.4.1.

**Comment by pitaj** [comment]
Yeah, you're doing something wrong. This project is not anywhere close to
being finished.

I'm not even actively developing right now. It doesn't even hook into git.

**Comment by xuv** [comment]
Ha. Sorry to hear this. I really was looking for something similar as your project. I'm a frontend designer. So I could have helped here. I also have feature suggestions of course. That you can't find in the Github Desktop app :) So a big question: do you have plans to come back to this piece of software and maybe a time frame. I'd love to help if you think it's worth it.

**Comment by pitaj** [comment]
I do plan on returning. I'm planning on coming back to it after finishing
some private work (and when my school schedule permits spending extra time
on this). That will probably be within the next three months.

On returning to the project, I will probably use React and Redux for the
frontend. I'd love to have any help I can get, but if you're experienced
with React that would be awesome.

I'm developing this primarily for Linux compatibility because there aren't
any good looking easy to use Linux git GUIs.

**Comment by xuv** [comment]
Ok. Very interesting. Let's keep in touch. I do not have React/Redux experience. But I can learn. 
I like the "Github Desktop" clean interface and it seems you want to go this way. So that's nice. My idea is to implement more visualizing tools, suitable for graphic files like SVG for example. I have "proof of concept" [here](https://github.com/xuv/design-with-git). It dates back a little and a first go at it. 
But there is a high demand for git and git diff gui tools for designers. That's why I got intersted in your code. To see if I could implement that on top of it.
